# -*- coding: utf-8 -*-
"""Github_colab_token.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QjYjKwprlDldRRnYzeoHQ0Oy_c-SrkU3
"""

username='contactmansi'
git_token='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'